### PR TITLE
Support attaching file metadata, and constrain upload concurrency

### PR DESCRIPTION
**Pull request by haf**
I'm uploading rather a few (~250 of them) static files and that got stuck on uploading them with this plugin.

I'd also like to serve them with a CDN with nice cache headers.

### CODE REVIEW

**Comment by haf** [comment]
It should be noted that when I link my github I get:

> ERROR in WebpackGoogleCloudStoragePlugin: undefined

Even with debug logging, so that's a wee bit frustrating and I can't tell whether it's yarn's package loader that doesn't understand how to pack with webpack or if I made a mistake in the code.

**Comment by haf** [comment]
With this prepare step, it works to ref from gh.

**Comment by shaunwarman** [comment]
LGTM, may think about retries too. This may help [smart-queue](https://github.com/shaunwarman/smart-queue)

**Comment by haf** [comment]
Retries are already handled in the client.

**Comment by syndbg** [comment]
@haf  LGTM, is it good for approval and merge?

**Pull request merged**
